require:
  - standard
  - rubocop-sequel
  - rubocop-rspec
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Exclude:
    - public/**/*
    - vendor/**/*

Bundler/DuplicatedGem:
  Enabled: false # ignore duplicated gem errors because we will have duplicated gems when dual booting
RSpec/BeforeAfterAll:
  Enabled: false
