require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - public/**/*
    - vendor/**/*

Bundler/DuplicatedGem:
  Enabled: false # ignore duplicated gem errors because we will have duplicated gems when dual booting
